name: 'Publish application'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.0.x

        # Generate the website
        - name: Publish
          run: dotnet publish src/Set.Web/Set.Web.csproj --configuration Release --output artifacts
        
        - name: Run unit tests
          run: dotnet test --no-restore --verbosity normal test/Set.UnitTests/Set.UnitTests.csproj

         # changes the base-tag in index.html from '/' to 'setgame' to match GitHub Pages repository subdirectory
        - name: Change base-tag in index.html from / to setgame
          run: sed -i 's/<base href="\/" \/>/<base href="\/setgame\/" \/>/g' artifacts/wwwroot/index.html

         # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
        - name: Add .nojekyll file
          run: touch artifacts/wwwroot/.nojekyll
          
        - name: Deploy to Github Pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
            BASE_BRANCH: master # The branch the action should deploy from.
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: artifacts/wwwroot # The folder the action should deploy.
            SINGLE_COMMIT: true